//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratory.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzer_job
    {
        public long job_code { get; set; }
        public System.DateTime datetime_receipt_order { get; set; }
        public System.DateTime datetime_service { get; set; }
        public long analyzer_code { get; set; }
    
        public virtual analyzer analyzer { get; set; }
    }
}
