//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratory.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long order_code { get; set; }
        public System.DateTime creation_date { get; set; }
        public string customer_login { get; set; }
        public long service_code { get; set; }
        public long order_status_code { get; set; }
        public long service_status_code { get; set; }
        public int days_to_complete { get; set; }
    
        public virtual order_status order_status { get; set; }
        public virtual service service { get; set; }
        public virtual service_status service_status { get; set; }
        public virtual user user { get; set; }
    }
}
