//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratory.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_rendered
    {
        public long service_code { get; set; }
        public System.DateTime date_of_service { get; set; }
        public string user_login { get; set; }
        public long analyzer_code { get; set; }
    
        public virtual analyzer analyzer { get; set; }
        public virtual user user { get; set; }
    }
}
